# ==============================================================
# = GestUser - Servizio Gestione Utenti 
# ==============================================================

server:
  port: 8019
spring:
  application:
    name: GestUser
# ==============================================================
# = MONGODB Parameters
# ==============================================================
  data:
    mongodb:
      authentication-database: admin
      database: ms-users
      host: 192.168.56.101
      password: Stefano_123
      port: 37017
      username: StefanoUser
