spring:
    application:
        name: Zuul Server

server:
    port: 8765
    tomcat:
        max-threads: 5

## ZUUL PARAMETERS
zuul:
    host:
        connect-timeout-millis: 20000
        socket-timeout-millis: 30000
    prefix: /roma/gateway
    strip-prefix: true
    ignored-services: '*'
        
## ROUTE PARAMETERS
    routes:
        tiberio: 
            path: /get/tiberio/**
            serviceId: Tiberio-ms
            sensitive-headers: Cookie,Set-Cookie ##disabilita la propagazione dei cookie ma garantisce quella dei token

Tiberio-ms:
    ribbon:
        ReadTimeout: 60000
        ConnectTimeout: 30000
        MaxTotalHttpConnections: 500
        MaxConnectionsPerHost: 100

hystrix:
    command:
        Tiberio-ms:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 90000

eureka:
    instance:
        lease-expiration-duration-in-seconds: 20
        lease-renewal-interval-in-seconds: 15
        instance-id: ${server.port}-ZUUL SERVER

    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl: 
            defaultZone: ${EUREKA_URL:http://user:Eureka_123_user@localhost:8761/eureka/}
