FROM mongo
 
# Update apt-get sources AND install MongoDB
RUN apt-get update && apt-get install nano

MAINTAINER nicola.larocca@xantrix.it

# Create the MongoDB data directory
RUN mkdir -p /data/db

# Expose port #37017 from the container to the host
EXPOSE 37017

# Set /usr/bin/mongod as the dockerized entry-point application
ENTRYPOINT ["/usr/bin/mongod"]

# sudo docker build -t my_mongodb .
# sudo docker run -d -p 37017:27017 -v ~/data:/data/db mongo
# mongo --port 37017
# docker run -d --net=Mongonet -p 37017:27017  -v ~/data:/data/db my_mongodb
