version: '3.3'

networks: 
  ntpgsql:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/24

services:
  mongodb:
    build:
      context: .
    restart: unless-stopped
    container_name: mongodb2
    volumes: 
      - data-volume:/data/db2
    networks: 
        ntpgsql:
          ipv4_address: 172.23.0.5
    ports:
      - target: 27018
        published: 37018
        protocol: tcp
        mode: host


volumes:
  data-volume:

